// GENERATED BY MITOSIS

import { Fragment, component$, h } from "@builder.io/qwik";
export const Button = component$((props) => {
  return (
    <a
      style={{
        border: "2px solid #000",
        borderRadius: "10px",
        padding: "10px",
      }}
    >
      <span>{props.text}</span>
    </a>
  );
});
export default Button;
