// GENERATED BY MITOSIS

import { Fragment, component$, h } from "@builder.io/qwik";
export const Html = component$((props) => {
  return (
    <html lang={props.lang} {...props.props}>
      {props.content}
    </html>
  );
});
export default Html;
